slsa-framework/slsa-github-generator

- .github/workflows/pre-submit.yml
- github/oidc.go
- github/oidc_test.go
- github/oidctest.go
- slsa/provenance_test.go
> Pre submit

- cmd/slsa-github-generator/attest.go
- cmd/slsa-github-generator/attest_test.go
> Allow whitespace in subject name.

- cmd/slsa-github-generator/attest.go
- signing/sigstore/signer.go
Return log entry object so that the caller can output information about log ID.
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
> Return log entry from rekor upload call

- cmd/slsa-github-generator/attest.go
- signing/sigstore/signer.go
Make signing library more generic for intoto statements.
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
> Make Sign take generic intoto.Statement

- slsa/github.go
- slsa/github_test.go
`workflow` is not present in all event payloads so we'll need to go back to using `workflow` from the `github`context for now.
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads
Updates #11
> Revert back to using github.workflow as entrypoint

- .github/actions/detect-workflow/Dockerfile
The previously used distroless sha seems to have had missing layers as I got a `ApplyLayer exit status 1 unexpected EOF` when attempting to execute the action.
> Fix sha for distroless

- CODEOWNERS
@joshuagl is in the original Go repo, but is missing from this one.
> ✨ Add joshuagl to CODEOWNERS

- github/oidc.go
- github/oidc_test.go
- github/oidctest.go
`net/url.Parse` does not return an error when the url is empty so `OIDCClient` gets all the way to fetching a token with a URL like `?audience=...` before failing.
This PR changes it so that creating the OIDC client fails when the `ACTIONS_ID_TOKEN_REQUEST_URL` environment variable is empty with a (hopefully) better error message.
> Return an error when OIDC server not available

- slsa/buildtype.go
- slsa/provenance_test.go
The verifier expects all fields to be populated, even if they are empty. (see https://github.com/slsa-framework/slsa-verifier/blob/main/pkg/provenance.go#L596)
We did not catch this via the pre-submits because it's only triggered on push/tag events; and we can only tests these thoroughly in the e2e tests.
This PR should fix https://github.com/slsa-framework/slsa-github-generator/issues/159 and https://github.com/slsa-framework/slsa-github-generator/issues/156
> 🐛 Always include context fields

- .github/actions/detect-workflow/action.yml
- .github/actions/detect-workflow/main.go
- .github/actions/detect-workflow/main_test.go
Fix the detect-workflow action to get the github context from environment variables. The `github` context is not available in `actions.yml` so we can't use it as we have with reusable workflows.
We should consider using go-githubactions (#153) to get and manage the context as it will work within both actions and reusable workflows.
> Fix reading github context in detect-workflow

- .github/workflows/pre-submit.reviewdog.yml
- .yamllint.config.yaml
Fixes #53
Adds pre-submits that run linters over code and add review comments to PRs.
- golangci-lint for Go code (note that many linters are disabled due to not supporting Go 1.18 - https://github.com/golangci/golangci-lint/issues/2649)
- shellcheck and shfmt for shell code.
- yamllint for yaml
> Add linter pre-submits

- .github/workflows/builder_go_slsa3.yml
This is causing me failures: https://github.com/asraa/slsa-example/actions/runs/2502778013
[build / upload-assets](https://github.com/asraa/slsa-example/runs/6901412245?check_suite_focus=true#step:2:16)
Unable to find an artifact with the name: binary-linux-amd64
This is because binary-upload is not required for the upload-assets job.
> fix: require binary upload before binary download

- .github/workflows/builder_go_slsa3.yml
A ref was not updated, resulting in:
```
Fetching the builder with ref: 
Builder referenced by hash: 
Resolving...
Tag not found for 
```
when using the pre-built builder binary. I caught this during the pre-release test
> 🐛 Ref name update

- internal/builders/generic/README.md
* Fixes broken links and a typo
* Clarifies the expected format of the decoded value of the input `base64-subjects`.
Signed-off-by: Chip Zoller <chipzoller@gmail.com>
> minor fixes, updates

- .github/workflows/release.yml
The two builds are still colliding on their name are the same. This PR forces each build to run sequentially.
We will fix this once we have multi-build support for Go builder
> 🐛 Release sequentially

- internal/builders/go/main.go
- internal/builders/go/pkg/provenance.go
- Refactored the implementation to accept the interface instead of the
concrete implementation within the function.
- With this change `GenerateProvenance` can be tested with mocks. At the
moment there aren't any unit tests for `GenerateProvenance`.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Refactor - Use interface for rekor and fulcio

- internal/builders/go/pkg/build_test.go
- internal/builders/go/pkg/testdata/go/go.mod
- internal/builders/go/pkg/testdata/go/main.go
- Included tests for build.go
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Test : Included tests for build.go

- .github/actions/detect-workflow/main.go
- .github/workflows/generator_generic_slsa3.yml
Related #376
I'm not sure why but it seems that in `pull_requests` (even though we don't really support them, and possibly other triggers) sometimes the `detect-workflow` action returns empty strings in the repository and/or ref outputs without producing an error. If fed directly into a later `checkout` action this checks out the repository in the `github` context (not the slsa-github-generator) repo.
This PR causes the `detect-workflow` action to return an error if no repository or ref are found.
> Return an error if repo/ref not detected

- README.md
- internal/builders/generic/README.md
Explain the difference between generic generator and builders
Add example to generate provenance in combination with Goreleaser
Later, we can add an example for docker images and other ecosystems there.
closes https://github.com/slsa-framework/slsa-github-generator/issues/405
> 📖 Update doc

- .github/actions/checkout-go/action.yml
- .github/actions/compute-sha256/action.yml
- .github/actions/generate-builder/action.yml
- .github/actions/secure-download-artifact/action.yml
- .github/workflows/pre-submit.e2e.generic.default.yml
- .github/workflows/pre-submit.e2e.go.config-ldflags-main-dir.yml
Updates #452 
Updates references in re-usable actions to point to a repository sha and not require a checkout of the repository.
We will need to reference re-usable actions in our workflow pre-submits after this PR is merged so workflow pre-submits are disabled by the PR temporarily. They will be re-enabled in subsequent PR #453
NOTE: The "verify" required status check was removed from the repository branch protection rules to allow us to commit this PR. This will also be restored for #453
> Update actions ref

- .github/actions/generate-builder/action.yml
- .github/actions/secure-download-artifact/action.yml
- .github/actions/secure-upload-artifact/action.yml
- .github/workflows/builder_go_slsa3.yml
- .github/workflows/generator_generic_slsa3.yml
Updates all references to internal actions.
This command did the trick (at least for now).
```
find .github/ -name '*.yaml' -o -name '*.yml' | xargs sed -i 's/uses: slsa-framework\/slsa-github-generator\/\.github\/actions\/\(.*\)@[a-f0-9]*/uses: slsa-framework\/slsa-github-generator\/.github\/actions\/\1@49e648aa7f5f4f88513b6cd54f6b189516184e6b/'
```
> Update references to reusable actions.

- .github/actions/detect-workflow/main.go
- .github/actions/detect-workflow/main_test.go
This fixes OIDCClient creation errors after updating the detect-workflow action. This only effects our pre-submits that run via `pull_request` triggers. We need to merge this PR and then upgrade actions and workflows to the merge commit sha.
Ex. https://github.com/slsa-framework/slsa-github-generator/runs/7143588115?check_suite_focus=true
> Avoid OIDC client creation errors on PRs

- .github/workflows/generator_generic_slsa3.yml
The `BUILDER_DIR` environment variable was never added to the generic workflow in #438 
Fixes the following error:
`./.github/actions/generate-builder/generate-builder.sh: line 7: cd: /generic: No such file or directory`
> Add BUILDER_DIR to generic workflow

- .github/workflows/builder_go_slsa3.yml
Updates #469 
Fixes "hashes do not match" error when running the Go workflow. This adds the `builder` job as a dependency for `upload-assets` so that the outputs from `builder` can be used.
> Add builder as dependency of upload-assets

- .github/workflows/scorecards.yml
Adds `tag=` to actions references in scorecard.yml so that renovate bot doesn't update them to HEAD.
> Add tag= to actions in scorecard.yml

- .github/actions/prng/action.yml
- .github/actions/rng/action.yml
This is part of https://github.com/slsa-framework/slsa-github-generator/issues/500 in order to generate random names.
In a follow-up PR, I will use names as `some-name-<random>`
> feat: Add a RNG Action

- .github/workflows/generator_generic_slsa3.yml
- internal/builders/generic/attest.go
- internal/builders/generic/attest_test.go
See https://github.com/slsa-framework/slsa-github-generator/issues/544
This PR adds an input to the generic re-usable workflow for the attestation filename.
> feat: Input argument for the name of attestation of generic workflow

- .github/workflows/generator_generic_slsa3.yml
closes https://github.com/slsa-framework/slsa-github-generator/issues/580
> fix: upload-asset option in generic generator

- internal/builders/generic/README.md
Allows using either Stack or Cabal build tools
Tested via example repo ([Cabal](https://github.com/mihaimaruseac/slsa-lvl3-generic-provenance-in-haskell-example/blob/v0.0.1.1/.github/workflows/ci.yaml), [Stack](https://github.com/mihaimaruseac/slsa-lvl3-generic-provenance-in-haskell-example/blob/v0.0.1.0/.github/workflows/ci.yaml)).
Also did some cleanup (removed trailing whitespace, fixed off-by-one errors)
> Haskell provenance

- internal/builders/generic/README.md
Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>
Does #595 after the formatting from #596, with the same layout
> Add provenance for Haskell

- README.md
- internal/builders/container/README.md
- internal/builders/generic/README.md
> Add links to milestones as a roadmap

- .github/workflows/generator_container_slsa3.yml
Fixes #613
This PR removes legacy env vars from the container workflow. These environment variables were previously used by the scripts that are now part of the [`generate-builder`](https://github.com/slsa-framework/slsa-github-generator/tree/main/.github/actions/generate-builder) action when the script was invoked directly by the workflow itself.
> Remove legacy env vars

- .github/workflows/scripts/pre-submit.e2e.generic.default.sh
- internal/builders/container/README.md
- internal/builders/generic/README.md
- internal/builders/generic/attest.go
> Update buildType of generic generator

- internal/utils/path_test.go
Running unit tests created a file at `internal/utils/existing_file` which was left over after tests completed. This PR updates the test to use temporary directory as the current working directory for the tests.
> Use a temp dir for cwd in tests

- README.md
> Update availability information of builders

- .github/actions/generate-builder/action.yml
- RELEASE.md
This sets the expected sha256 of the v1.3.0 slsa-verifier released binary.
Download the binary and provenance from https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.3.0
Clone the slsa-verifier repo, compile and verify the provenance:
$ git clone git@github.com:slsa-framework/slsa-verifier.git
$ cd slsa-verifier
$ (Optional: git checkout tags/v1.3.0)
$ go run ./cli/slsa-verifier -artifact-path slsa-verifier-linux-amd64 -provenance slsa-verifier-linux-amd64.intoto.jsonl -source github.com/slsa-framework/slsa-verifier -tag v1.3.0
Get the hash.
Either:
cat slsa-verifier-linux-amd64.intoto.jsonl | jq -r '.payload' | base64 -d | jq -r '.subject[0].digest.sha256'
or
sha256sum slsa-verifier-linux-amd64
The output hash should be the hash I'm …
> chore: update verifier to v1.3.0

- internal/builders/generic/README.md
Signed-off-by: Seth Michael Larson <sethmichaellarson@gmail.com>
> contents: write is required for the generic builder

- internal/builders/generic/README.md
Fix permissions used by the generic workflow in docs. `contents: write` is needed for writing artifacts to releases. This continues the doc fix that was made in #758 
> Fix permissions in generic workflow doc

- .github/workflows/generator_container_slsa3.yml
- internal/builders/container/README.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
> fix: type in OIDC word

- internal/builders/go/pkg/build_test.go
Temporarily comments out the test for `GoBuild.Run` due to it overwriting the execution context of the test runner.
Updates #771 
Signed-off-by: Ian Lewis &lt;ianlewis@google.com&gt;
> Temporarily disable Run test.

- internal/builders/go/main.go
- internal/builders/go/pkg/build_test.go
- internal/builders/go/pkg/provenance.go
- internal/builders/go/pkg/provenance_test.go
Fixes a panic that occurs when transparency log upload returns an error.
Depends on #772
> Fix log message for tlog upload

- internal/builders/go/main_test.go
> Update pwd code in unit-test

- .github/workflows/scripts/pre-submit.e2e.go.default.sh
- internal/builders/go/main_test.go
- internal/runner/runner.go
- internal/runner/runner_test.go
Updates #822 
Remove PWD from the environment variables in provenance build steps as it is redundant with the given working directory. `PWD` is set when executing the command but is not included in the environment variables that are added to the `buildConfig` in the provenance.
Before:
```json
"steps": [
{
"command": ["bash", "-c", "echo $STEP2"],
"env": [
"STEP2=fuga",
"PWD=/home/user"
],
"workingDir": "/home/user"
},
...
]
```
After:
```json
"steps": [
{
"command": ["bash", "-c", "echo $STEP2"],
"env": [
"STEP2=fuga"
],
"workingDir": "/home/user"
},
...
]
```
> Remove PWD from provenance env

- .github/workflows/builder_go_slsa3.yml
- .github/workflows/generator_container_slsa3.yml
- .github/workflows/generator_generic_slsa3.yml
Fixes #823 
- Adds call to the privacy-check to workflows. Each workflow gets a new `private-repository` input to override this check.
- The Go builder now has `actions: read` permissions in order to support private repos.
> Add call to privacy check to workflows

- .github/actions/privacy-check/action.yml
- .github/workflows/builder_go_slsa3.yml
- .github/workflows/generator_container_slsa3.yml
- .github/workflows/generator_generic_slsa3.yml
`contents: read` permissions aren't needed to read a repo object from the GitHub API. Only `metadata` scope is needed and that is given to workflows by default.
> Remove contents:read from privacy-check

- internal/builders/container/README.md
Fixes #389 
Adds an example to the container workflow docs of using a Kyverno policy to verify provenance.
> [docs] Verifying provenance with kyverno

- .github/actions/verify-checkout/action.yaml
Will also help debug a renovatebot PR that fails
> feat: add log when verify-checkout fails

- .github/actions/checkout-node/action.yml
- .github/workflows/builder_go_slsa3.yml
- .github/workflows/builder_node_slsa3.yml
- .github/workflows/pre-submit.actions.yml
This PR adds a new workflow `builder_node_slsa3.yml`. It contains the structure to build upon for follow-up PRs that will create the node builder itself.
> feat: Add npm builder workflow

- .github/actions/verify-checkout/action.yaml
This is the reason the pre-submits are currently failing for renovatebot.
> fix: verify-checkout uses wrong sha to validate for pull_requests

- .github/actions/generate-builder/action.yml
- RELEASE.md
Pending https://github.com/slsa-framework/slsa-verifier/pull/288/files
to fix https://github.com/slsa-framework/slsa-github-generator/issues/942
> update verifier version in actions

- README.md
- internal/builders/generic/README.md
- internal/builders/go/README.md
Previously, at some points across the different READMEs there were explanations on why it's necessary to refer the SLSA generators and builders using tags in the format @vX.Y.Z, but some of them were incomplete. This change adds a subtopic to the base README that contains all the explanation, and this subtopic is linked on other parts of READMEs that needs the explanation.
This issue was previously discussed with @laurentsimon
> Update READMEs to clarify that SLSA generators and builders must be referred by tag

- .github/actions/checkout-go/action.yml
- .github/actions/checkout-node/action.yml
Updates `checkout-go` and `checkout-node` to use `secure-checkout`. Updates to use the new version of `checkout-go` and `checkout-node`, as well as updating pre-submits will come on later PRs.
> Update checkout-(go|node) to use secure-checkout

- .github/actions/checkout-go/action.yml
- .github/actions/checkout-node/action.yml
- .github/actions/generate-builder/action.yml
- .github/workflows/builder_go_slsa3.yml
> Update ref for checkout-go

- .github/actions/secure-checkout/action.yaml
Updates #968
This PR changes the `sha` input for `secure-checkout` to `ref` and allows passing git a `ref` or `sha`. The action now performs validation by looking up the `ref` in the API and checking that the sha digest returned by the API and the sha checked out locally match. This may not necessarily satisfy the TLS interception issue brought up on #626 but at least makes it a little harder to fake a checkout.
We need to support `ref` in `secure-checkout` because we need to be able to checkout the builder using a tag reference. This is because we recommend users call our workflows using a release tag.
e.g.
```yaml
uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.2.0
```
This results in `detect-env` action returning something like …
> Support ref in secure-checkout

- .github/actions/checkout-go/action.yml
- .github/actions/checkout-node/action.yml
- .github/actions/generate-builder/action.yml
Updates #968
Requires #1005 
Updates `checkout-go` and `checkout-node` to use the newer version of `secure-checkout` that supports the `ref` input.
> Use ref for secure-checkout

- .github/actions/detect-workflow/main.go
- .github/actions/detect-workflow/main_test.go
This fixes the ref from detect-env in pull_request of the workflows to be a SHA, rather than a not-fully-formed GITHUB_HEAD_REF
> fix: fix ref from detect-env in pull_request

- .github/workflows/builder_go_slsa3.yml
- .github/workflows/builder_node_slsa3.yml
- .github/workflows/generator_container_slsa3.yml
- .github/workflows/generator_generic_slsa3.yml
> update refs to generate-builder

- .github/actions/checkout-go/action.yml
- .github/actions/checkout-node/action.yml
This pulls in Ian's bug fix for secure-checkout https://github.com/slsa-framework/slsa-github-generator/commit/ea457948e6a989e9818304dcb4f15fb4ce6765d6 and updates the callers `checkout-go` and `checkout-node`
> fix: use updated ref for secure-checkout

- .github/actions/generate-builder/action.yml
- .github/workflows/builder_go_slsa3.yml
Updates ref from https://github.com/slsa-framework/slsa-github-generator/commit/c2e7da4c53f2703d9af77f8d1483078c8fd3477e for the `checkout-go` action.
One more after this!
> fix: update refs for checkout-go

- .github/actions/rng/action.yml
- internal/builders/container/README.md
- internal/builders/generic/README.md
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
`set-output` was deprecated.
AS IS
```
echo '::set-output name={name}::{value}'
```
TO BE
```
echo "{name}={value}" >> $GITHUB_OUTPUT
```
> fix: use GITHUB_OUTPUT instead of deprecated set-output command

- RELEASE.md
> Fix reference to generic generator

- README.md
- RENOVATE.md
As proposed in https://github.com/slsa-framework/slsa-verifier/issues/12#issuecomment-1280619107 it might be helpful for other users to have a handy renovate snippet to follow the README's guidance on using tags instead of digests.
Signed-off-by: Fabian Kammel <fk@edgeless.systems>
> Document renovate exception for tags over digest.

- .github/actions/README.md
- .github/workflows/builder_go_slsa3.yml
- .github/workflows/builder_node_slsa3.yml
- .github/workflows/generator_container_slsa3.yml
- .github/workflows/generator_generic_slsa3.yml
Need https://github.com/slsa-framework/slsa-github-generator/pull/1087 and https://github.com/slsa-framework/slsa-github-generator/pull/1107 to be merged first.
> feat: update ref

- .github/workflows/builder_go_slsa3.yml
- .github/workflows/builder_node_slsa3.yml
- .github/workflows/generator_container_slsa3.yml
- .github/workflows/generator_generic_slsa3.yml
- .github/workflows/release.yml
- .github/workflows/scripts/pre-release/references.sh
- RELEASE.md
This will fix the current error that affects all e2e tests.
The PR also uses `@main` for all the actions we use. We will set these to the tag release before release. I have added pre-release workflows to verify the release tag and the reference of the Actions is the same' and amended the RELEASE.md accordingly.
> fix: checkout uses the wrong repository

- .github/actions/generate-builder/action.yml
- .github/workflows/pre-submit.actions.yml
- .github/workflows/pre-submit.e2e.generic.default.yml
- .github/workflows/pre-submit.e2e.go.config-ldflags-main-dir.yml
We need to temporarily need to disable the reusable workflow pre-submits because they use `generate-builder@main` and it's broken at `main`. Will follow up with a later PR to re-enable them.
Also added pre-submits so we hopefully don't break `generate-builder` at `main` again.
Also updates adversarial pre-submits so that the check is done as part of each job. This is so that checks don't show up as failed in PRs.
> Fix privacy-check checkout

- .github/workflows/pre-submit.actions.yml
Temporarily disables the `generate-builder` pre-submit for `compile-builder: false` due to #1163
> Temporarily disable pre-submit

- .github/actions/generate-builder/action.yml
- RELEASE.md
Pending https://github.com/slsa-framework/slsa-verifier/pull/347/
To verify, see that PR:
1. Download the binary and provenance from https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.3.2 (or the other)
2. Clone the slsa-verifier repo, compile and verify the provenance:
```
$ git clone git@github.com:slsa-framework/slsa-verifier.git
$ cd slsa-verifier
$  go run ./cli/slsa-verifier verify-artifact ~/Downloads/slsa-verifier-linux-amd64 --provenance-path ~/Downloads/slsa-verifier-linux-amd64.intoto.jsonl --source-uri github.com/slsa-framework/slsa-verifier --source-tag v1.3.2 --source-branch release/v1.3
```
3. Get the hash.
Either:
```
cat slsa-verifier-linux-amd64.intoto.jsonl | jq -r '.payload' | base64 -d | jq -r …
```
> verifier: update verifier version to v1.3.2

- internal/builders/generic/README.md
The generic generator's README still used @v1.2.0, this PR bumps all references to the current @v1.2.1.
> 📖 Bump version tag in examples

- renovate.json
This should hopefully group up some updates so that they are easier to merge.
The intention of the update is as follows:
- Go updates that are minor and patch version updates should be grouped into a single PR. Major updates would not be grouped.
- npm dependencies that are minor and patch version update should be grouped into a single PR. Major updates would not be grouped.
- npm devDependencies should be grouped into a single PR.
- GitHub actions dependencies should be grouped.
> Group updates for renovate

- internal/builders/generic/attest.go
- internal/builders/generic/attest_test.go
- internal/utils/path_test.go
Updates https://github.com/slsa-framework/slsa-github-generator/issues/1225
The generic SLSA 3 generator attests to subjects given as input and their digest. However, if the subject is in a sub-directory, then it will fail creating the attestation because the sub-directory doesn't exist.
This retrieves the Base for the subject name, instead of the full path name.
@ianlewis I could also have created the sub-directory, but that made a lot less sense to me.
> [generic] fix attestation file creation when subject names are in subdirectories

- .github/workflows/release.yml
- RELEASE.md
Updates the release docs.
1. Tagging happens at the beginning in order to update workflow reference. This means that Pre and Post release tests can be run in sequence before code-freeze and ensures we don't wait to find errors in release tests.
2. Updated commands to be easier to copy & paste.
> Update RELEASE docs

- internal/builders/go/pkg/config.go
- internal/builders/go/pkg/config_test.go
- internal/builders/go/pkg/testdata/releaser-valid-envs-multiple-equal-signs.yml
- internal/builders/go/pkg/testdata/releaser-valid-envs-no-value.yml
If .slsa-goreleaser.yml contains an env var with multiple '=' signs:
```
env:
- CGO_ENABLED=1
- CGO_CFLAGS=-mmacosx-version-min=11.0
```
the 'build dry project' GH workflow step fails with "invalid environment
variable: CGO_CFLAGS=-mmacosx-version-min=11.0"
This is caused by the way the env vars are parsed in GoReleaserConfig:setEnvs
which only allow for a single '=' sign.
This commit fixes this by splitting the env string at the first equal sign,
first part is the env var name and won't contain '=' signs, second part
is its value and can contain any number of '='.
This also adds unit tests for this situation, and for env vars with no
values (`CGO_CFLAGS=`).
This fixes https://github.com/slsa-framework/slsa-github-generator/issues/1231
> builder: go: Allow equal signs in env vars

- internal/builders/generic/README.md
After exposing the expected provenance format, clarify that the actual result will be encapsulated in a DSSA envelope and encoded in base64. Also includes quick command to decode the human readable JSON.
Closes #1186
Signed-off-by: Diogo Teles Sant'Anna <diogoteles@google.com>
> docs(generic-generator): clarify that created provenance is encapsulated

- .github/workflows/builder_go_slsa3.yml
- .github/workflows/builder_nodejs_slsa3.yml
- .github/workflows/generator_container_slsa3.yml
- .github/workflows/generator_generic_slsa3.yml
Please also review the release notes at https://github.com/slsa-framework/slsa-github-generator/releases/tag/v1.3.0
#label:release v1.3.0
> Start code freeze for v1.3.0

- renovate.json
Update renovate config so that Go itself is updated in it's own PR rather than being grouped together with Go packages.
> Exclude go from renovate PR grouping

- .github/workflows/generator_container_slsa3.yml
- internal/builders/container/README.md
Fixes #1256 
Fixes #1257 
Updates #547 
1. Sets top level token permissions for the container generator workflow.
2. Updates container generator workflow to no longer require `package: write` permissions on the GHA token. Instead we require users of ghcr.io to login using a PAT.
> Update GHA token permissions for generic container workflow

- .github/workflows/generator_container_slsa3.yml
- internal/builders/container/README.md
Reopens #1257 
Reverts most of #1258 but leaves in place top level permissions for the generic container workflow. This is because cosign seems to use the ambient token to retrieve data from the OCI registry for signing rather than using the provided registry password.
> Revert package perms

- .github/actions/detect-workflow/main.go
- .github/workflows/generator_generic_slsa3.yml
- internal/builders/container/README.md
- internal/builders/generic/README.md
I recently migrated my pipelines to v1.4.1 and noticed there are some warnings refering to `set-output` left. I have found #1004 which makes it sounds these last references were missed during that cleanup.
In case this was not on purpose, here is a suggestion on how we could migrate to `GITHUB_OUTPUT`. 🙂 
The only reference I have left (that I could find) is: https://github.com/datosh/slsa-github-generator/blob/2c6620ba8f96507604e3e76364a19129fbf76cc2/github/set_output.go#L36
I left that in for @asraa once set-output is EOL, as stated by comment.
Signed-off-by: Fabian Kammel <fk@edgeless.systems>
> migrate deprecated set-output to GITHUB_OUTPUT

- .github/workflows/generator_generic_slsa3.yml
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/1310
( I hope)
I think there was a bash syntax error here
```
set -euo pipefail
id=""
if [[ -n "$RELEASE_ID_NEW_TAGS"]]; then
id="$RELEASE_ID_NEW_TAGS"
elif [[ -n "$RELEASE_ID_TAG_NAME"]]; then
id="$RELEASE_ID_TAG_NAME"
else
echo "internal error"
exit 1
fi
echo "::set-output name=id::$id"
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
BUILDER_BINARY: slsa-generator-generic-linux-amd64
BUILDER_DIR: internal/builders/generic
RELEASE_ID_NEW_TAGS: 8508[3](https://github.com/slsa-framework/example-package/actions/runs/3625957411/jobs/6114562079#step:6:3)076
RELEASE_ID_TAG_NAME: 
/home/runner/work/_temp/9ce6b8[4](https://github.com/slsa-framework/example-package/actions/runs/3625957411/jobs/6114562079#step:6:4) …
```
> fix: fix bash syntax on release tag names

- internal/builders/container/README.md
Fixes #1320
This PR removes the project status section of the container generator's README now that it's GA.
Docs for other GA builders/generators don't include a project status section. The section was removed rather than being updated to be consistent with other docs.
> docs: Update container generator project status

- internal/builders/container/README.md
- internal/builders/generic/README.md
Closes #707.
This PR adds documentation on how to adding provenance for matrix-strategy builds. It handles both the single-file and multi-file scenarios (where maintainers want a single file for all artifacts from all iterations or a different file for each iteration, respectively).
The documentation is stored within `./internal/builders/generic/README.md`, and a reference has been added to `./internal/builders/container/README.md` (this method has not been tested with the container generator, but should work there as well).
> docs: Add documentation on matrix-strategy builds

- internal/builders/container/README.md
This matches `jobs.provenance.with` in the next example.
Signed-off-by: raghavkaul <8695110+raghavkaul@users.noreply.github.com>
> Typo: README.md

- .github/workflows/generator_generic_slsa3.yml
- .github/workflows/scripts/pre-submit.e2e.go.default.sh
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/1327
It seemed like the `repository` and `ref` were not set during the upload-assets job, and because of this, example-package was checked out instead of the builder repository. This was because that job did not require `detect-env` where the `repository` and `ref` come from, so they were probably resolved before that job completed.
> fix(generic): fix bug in generic workflow to set pre-requisite job

- .github/workflows/scripts/pre-submit.e2e.go.default.sh
Adds back the go presubmit verification of arch and os, updating the arch to ubuntu22 
See commit here:
https://github.com/slsa-framework/slsa-github-generator/commit/9faebcac31ac83ab693adf4e0dfe0d46c70c81cf
@ianlewis should we entirely remove these? @laurentsimon pointed out it's captured in materials: https://github.com/slsa-framework/slsa-github-generator/blob/9faebcac31ac83ab693adf4e0dfe0d46c70c81cf/internal/builders/go/pkg/provenance.go#L159
If so, I can update this PR to remove those and replace these checks with the runner material check.
> fix: add back go presubmit verification of arch and os

- .github/workflows/builder_docker-based_slsa3.yml
- .github/workflows/pre-submit.e2e.docker-based.default.yml
This updates the docker-based workflow to be a working with placeholder outputs. Adds a pre-submit job that checks for workflow correctness right now (but performs no verification yet).
The builder output and custom build definition are hard-coded, and the predicate/attestation/envelope generation is placeholder. 
The placeholder actions will be added in separate PRs with tests. These will also be re-used in the delegator workflow. Once the delegator workflow is done, I will also test using the completed builder binary in the delegator.
@rbehjati
> [docker] update docker-based workflow and add pre-submit workflow

- internal/builders/docker/commands.go
- internal/builders/docker/main.go
Builds on top of #1267, and adds the top-level command line tool, with some placeholder code. 
Todo: Output format for build command: https://github.com/asraa/slsa-github-generator/blob/main/.github/workflows/builder_docker-based_slsa3.yml#L245-L253
> Add top-level command line tool

- .github/actions/detect-workflow/Dockerfile
- .github/workflows/scripts/verify-base-images.sh
Updates #1401
Also updates the verification script to only check the SHA of the image rather than the whole output of the `docker trust inspect` command.
> Update golang image sha

- .github/workflows/scripts/pre-submit.actions/setup-token.sh
Signed-off-by: laurentsimon <laurentsimon@google.com>
closes https://github.com/slsa-framework/slsa-github-generator/issues/1416
I have also made the setup-token pre-submit as required in the branch protection settings.
> fix: setup-token pre-submits

- .github/actions/generate-attestations/action.yml
- .github/actions/generate-attestations/package-lock.json
Signed-off-by: laurentsimon <laurentsimon@google.com>
This PR updates json5 dependency.
```shell
$ npm audit report
json5  <1.0.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fix available via `npm audit fix`
node_modules/json5
1 high severity vulnerability
```
> fix: existing vuln in json5

- internal/builders/go/pkg/config.go
- internal/builders/go/pkg/config_test.go
Adds config file path to error messages to make it clearer these are error messages that occurred during config parsing.
> chore: Improve config parsing error messages

- internal/builders/docker/commands.go
This was introduced here https://github.com/slsa-framework/slsa-github-generator/pull/1388/commits/e6231cc2161b8924d56ae1abea0da49ce9a246fb but there is a cleanup function that is set before the error on `db` is checked, which gives a nilptr exception. 
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/1501
/review @rbehjati
> fix: fix defer cleanup before error checking db

- .github/workflows/builder_docker-based_slsa3.yml
- .github/workflows/pre-submit.e2e.docker-based.default.yml
This updates the docker based workflow to use the resolved `buildDefinition` and completes the workflow to sign the attestation. The presubmit is also updated to be functional.
Passing run: https://github.com/asraa/slsa-github-generator/actions/runs/3878872921
The next missing pieces:
* Populate rest of predicate with GH context
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/1499
cc @rbehjati
> feat(docker): update docker based workflow to use buildDefinition and sign

- RELEASE.md
Fixes #1296 
Adds instructions to RELEASE.md for creating release candidates as part of the release process.
I will use this version of the instructions for the upcoming v1.5.0 release.
> docs: Add instructions for release candidates to RELEASE.md

- .github/workflows/scripts/e2e-utils.sh
- .github/workflows/scripts/e2e-verify.common.sh
The run fails because the `workflowPath` should be fully qualified, and `e2e_this_file` only returns the basename.
cc @laurentsimon
> fix: workflowPath in provenance is fully qualified

- .github/workflows/pre-submit.actions.yml
The path requires the matrix's action path.
Checkout seems to support expansion:
https://github.com/actions/upload-artifact#environment-variables-and-tilde-expansion
> ci: fix check-dist upload on failure

- .github/actions/detect-workflow/README.md
- .github/actions/detect-workflow/action.yml
- .github/actions/detect-workflow/main.go
- .github/workflows/builder_docker-based_slsa3.yml
I missed setting the `workflow` output in the job outputs. 
I didn't notice this, because during pre-submit detect-env doesn't catch `workflow` anyway.
Also updates the `action.yml` and `README.md`, because `workflow` was just the workflow path.
> fix: fix workflow output in docker-based workflow

- .github/workflows/scripts/e2e-verify.common.sh
See https://github.com/slsa-framework/slsa-github-generator/actions/runs/4160033579 for failure.
Removes the ArtifactValue wrapping from the old SLSA v1.0 draft format.
> fix: fix verify token schedule check on source

- .github/workflows/builder_docker-based_slsa3.yml
- .github/workflows/e2e.create-docker_based-predicate.schedule.yml
- .github/workflows/scripts/e2e-utils.sh
- .github/workflows/scripts/schedule.actions/verify-docker_based-predicate.sh
* Adds a schedule test for the `create-docker_based-predicate` action that exercises the builder ID option using detect-env's workflow. During pull request, we cannot detect the current reusable workflow path the caller invokes. 
* Fixed a repeated string issue in the action.
> test: add testing for docker based predicate creation

- .github/workflows/builder_docker-based_slsa3.yml
- internal/builders/docker/pkg/builder.go
- internal/builders/docker/pkg/builder_test.go
* Adds the option to specify a a source reference to the docker build definition, allowing the build definition source artifact to include the full URI with ref. The builder verifies that the ref matches the `git-commit-digest` specified.
```
{
"buildType": "https://slsa.dev/container-based-build/v0.1?draft",
"externalParameters": {
"source": {
"uri": "git+https://github.com/slsa-framework/slsa-github-generator@refs/heads/main",
"digest": {
"sha1": "e4cf1c15850a03ee3dc5a82159443513a5f31610"
}
},
"builderImage": {
"uri": "bash@sha256:9e2ba52487d",
"digest": {
"sha256": "9e2ba52487d"
}
},
"configPath": "internal/builders/docker/testdata/config.toml",
"buildConfig": {
"ArtifactPath": "config.toml",
"Command": [
"cp", …
```
> feat: add source ref to the docker build definition

- .github/workflows/builder_docker-based_slsa3.yml
This adds two outputs to the docker-based workflow, `provenance-name` and `build-outputs-name` to store the generated provenance and generated build artifacts.
This allows users to consume these at later steps.
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/1500
> feat: add workflow outputs to docker-based workflow

- .yamllint.yaml
Disables [`comments-indentation`](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments_indentation) for yamllint since often commenting out blocks of yaml cause indentation to not match up with uncommented code.
An example follows. In this case the commented `hoge` block does not match with the `bar` on the previous line. This is desirable however to maintain the proper indentation when the block is uncommented.
```yaml
main:
foo:
bar: "baz"
```
> chore: Disable comments-indentation for yamllint

- go.mod
- go.sum
- internal/builders/docker/README.md
- internal/builders/docker/commands.go
- internal/builders/docker/main.go
- internal/builders/docker/pkg/builder.go
- internal/builders/docker/pkg/builder_test.go
- internal/builders/docker/pkg/common.go
- internal/builders/docker/pkg/common_test.go
- internal/builders/docker/testdata/build-definition.json
- internal/builders/docker/testdata/slsa1-provenance.json
Fixes #1618 
Adds a `verify` subcommand as described in #1618. Fixes and updates the README and testdata used in the README and examples.
Signed-off-by: Razieh Behjati <razieh@google.com>
> fix: Add verify subcommand

- .github/workflows/scripts/e2e-verify.common.sh
I'm starting to think it would be good to run this during pre-submit at some point...
I can't think of the best way beyond a bunch of fakes that are just as hard to maintain
> fix: fix one more verify-token script check

- .github/workflows/builder_docker-based_slsa3.yml
- .github/workflows/delegator_generic_slsa3.yml
- internal/builders/docker/README.md
- internal/builders/docker/pkg/builder.go
- internal/builders/docker/pkg/builder_test.go
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/1638
* Adds a `provenance-name` input option to the docker builder to configure the name of the attestation that gets uploaded
* Updates docs
* Renames `provenance-name` output to `attestations-download-name` for consistency
* Fixes a bug when using a `--force-checkout` locally, the build output needs to be absolute to generate the relative path.
cc @rbehjati this will fix an issue I noticed in https://github.com/project-oak/oak/actions/runs/4312859723 where the attestation was using the same name. Also checkout the workflow output documentation for the location of the build/provenance output.
> feat: add a provenance-name input option to the docker builder

- .github/workflows/e2e.detect-workflow-js.schedule.yml
See run https://github.com/slsa-framework/slsa-github-generator/actions/runs/4334298905/jobs/7568100586#step:4:27
Fixes verification comparison of the workflow (something like .github/workflows/example.yml) emitted by `detect-workflow-js` and the expected value.
> fix: fix GITHUB_WORKFLOW check

- .github/workflows/e2e.create-docker_based-predicate.schedule.yml
The testadata build-definition.json includes a hard-coded SHA, while the verification script generally tests against the `GITHUB_SHA` env var.
> fix: fix schedule tests with fixed sha

- .github/workflows/generator_container_slsa3.yml
This PR fixes workflow failure for generic container.
* `--force` flag is removed by https://github.com/sigstore/cosign/pull/2399
* Use `--yes` instead of `--force`
> fix: Update cosign flag

- .github/workflows/scripts/schedule.actions/setup-token.sh
Fixes #1759
Updates the script to use the right import to get the `e2e_verify_decoded_token` function.
> fix: Fix setup-token script

- .github/workflows/scripts/e2e-utils.sh
- .github/workflows/scripts/e2e-verify.common.sh
May fix https://github.com/slsa-framework/slsa-github-generator/issues/1809
* RUNNER_NAME and RUNNER_VERSION may differ between the jobs that create the predicate and the one that verifies, so only test for presence of the field.
> fix: fix runner verification of predicate

- .github/workflows/builder_docker-based_slsa3.yml
- internal/builders/docker/README.md
In the case of public base images, registry-username or gcp username may both be empty
> fix: make registry-username optional

- .github/workflows/pre-submit.actions.yml
Updates `check-dist` to clean the package dist directory before building the package so that it does a clean comparison. This is most useful when files get moved around or renamed.
> ci: Do clean comparison in check-dist pre-submit

- internal/builders/docker/commands.go
- internal/builders/docker/pkg/builder.go
Currently, if the give output folder is not only, the `build` command only fails after the build is completed and when copying the files to the output folder. With this change this situation is detected earlier.
> fix:  Check that the output folder is empty

- .github/workflows/builder_nodejs_slsa3.yml
Fixes #1828
Fixes #1829
Adds access for the `--access` and `--tag` flags on `npm publish`.
> feat: Add support for access and tag flags to npm builder

- .github/workflows/builder_docker-based_slsa3.yml
- internal/builders/docker/pkg/builder.go
- internal/builders/docker/pkg/config.go
- internal/builders/docker/pkg/options.go
Tested with `build` and `dry-run` commands.
For `build` tested with an invalid image digest, and the errors are printed to console.
> feat: Add a verbose option to the docker-builder

- .github/workflows/builder_docker-based_slsa3.yml
- internal/builders/docker/README.md
Updates the predicate type version string in generate-attestations to v1.0 for docker-based builder.
This is needed to fix https://github.com/slsa-framework/slsa-github-generator/issues/1997 as I update https://github.com/slsa-framework/slsa-verifier/issues/561
> chore: update slsa version to v1.0 in docker-based workflow

- .github/workflows/builder_nodejs_slsa3.yml
This moves the npm cli fork from [ianlewis/cli@oob-provenance](https://github.com/ianlewis/cli/tree/oob-provenance) to  [slsa-framework/npm-cli@oob-provenance](https://github.com/slsa-framework/npm-cli/tree/oob-provenance).
The commits on the repo have been cleaned up to be a single patch on the v9.6.5 release of the npm cli.
> feat: Move npm cli fork to slsa-framework org

- .github/workflows/scripts/schedule.actions/verify-container_based-predicate.sh
The container-based predicate's resolvedDependencies contains (1) the source with repo & commit sha and (2) the builder binary reference. 
I didn't update the scheduled e2e testing script to check for both after adding both references.
Fixes:
https://github.com/slsa-framework/slsa-github-generator/actions/runs/5151801823/jobs/9277322271
> fix: fix test script for container_based predicate

- .github/workflows/e2e.create-container_based-predicate.schedule.yml
https://github.com/slsa-framework/slsa-github-generator/actions/runs/5159223240/jobs/9293876076
Fixes another issue - the e2e schedule script needs to update both references of the source in the buildDefinition.json.
> fix: fix another test script issue with scheduled predicate action

- .github/workflows/builder_gradle_slsa3.yml
- .github/workflows/builder_maven_slsa3.yml
Gradle and Maven builders referenced setup-token. Changed to use setup-generic now.
> feat: rename setup-token to setup-generic (slsa-framework#2176)

- internal/builders/nodejs/README.md
Fixes #2163 
Adds tests to the example in Node.js builder docs.
> docs: Update docs to include tests

- internal/builders/nodejs/build.sh
Fixes getting the filename from the result of `npm pack --json`. Some older versions return the incorrect file name.
This change falls back and attempts to determine the filename if the file is not initially found.
Fixes #2290  #2294 #2295 #2296 #2297 #2298 #2299
> fix: getting npm pack filename

- actions/nodejs/publish/action.yml
This installs the instance of npm used for publish in a temporary directory rather than polluting the user job global npm modules.
> fix: install npm in a temp directory

- internal/builders/nodejs/generate-layout.sh
Fixes #2359 
Fixes parsing of npm package names when non-scoped.
> fix: non-scoped package handling

- .github/workflows/delegator_generic_slsa3.yml
- .github/workflows/delegator_lowperms-generic_slsa3.yml
- .github/workflows/scripts/pre-submit.delegators/expected.diff
- BYOB.md
Due to https://github.com/actions/runner/issues/2274, we fetch the TRW workflow so it must be public. The GITHUB_TOKEN only lets us read private project repos, not the TRW rep.
> docs: Update BYOB doc

- .github/actions/secure-download-artifact/action.yml
- .github/actions/secure-download-folder/action.yml
- .github/workflows/generator_generic_slsa3.yml
As part of https://github.com/slsa-framework/slsa-github-generator/pull/2365, we added support for large files.
We forgot to update the "success" computation. This means that even though the sha256 may differ from the expected, the job continues and we never record the failure status.
I fix this in the PR. I also delete the downloaded folder / artifact if the sha256 don't match, to avoid a similar problem in he future
> fix: fail if large file sha256 does not match

- internal/builders/generic/README.md
The GitHub Actions runner sometimes masks the job output if it potentially contains an accessible secret. The new `base64-subjects-as-file` feature can be recommended to pass the artifact hashes using an existing file and bypass the job output masking issue.
See this discussion: https://github.com/orgs/community/discussions/37942
> docs: recommend base64-subjects-as-file for masked outputs issue

- internal/builders/maven/README.md
Updates the Maven documentation to remove two env vars from the example PW.
> feat: Maven builder: Remove env vars from example

- actions/gradle/publisher/README.md
- actions/gradle/publisher/action.yml
Adds a publisher for the Gradle builder to publish artifacts and provenance to the Maven Central Repository.
> feat: Add Gradle publisher

- .github/workflows/builder_gradle_slsa3.yml
- internal/builders/gradle/README.md
Adds documentation for the Gradle builder. 
Also removes the need for write-permissions for packages.
> feat: add documentation to gradle builder

- .github/workflows/builder_maven_slsa3.yml
- .github/workflows/publish_maven.yml
- internal/builders/maven/README.md
Write permissions are not needed for the lowperms delegator, so removing that from the Maven builder.
> feat: reduce package permissions in maven builder / publisher

- .github/workflows/scripts/pre-release/references.sh
- .github/workflows/scripts/pre-submit.actions/references.sh
- RELEASE.md
- actions/maven/publish/action.yml
- internal/builders/maven/action.yml
closes https://github.com/slsa-framework/slsa-github-generator/issues/2508
We need to keep in sync the checkout of the slsa-github-generator repo
> feat: Keep ref in sync for Maven Actions

- RELEASE.md
Updates RELEASE.md to:
- Add a command to update ref for maven actions for RC releases
- Add commands for updating the ref for `generate-builder` during adversarial verifier tests
> docs: Update RELEASE.md

- internal/builders/nodejs/README.md
- Adds a "known issues" section.
- Adds instructions on how to custom publish without using the `publish` action.
Related #2322
> docs: Update Node.js builder docs

- actions/nodejs/publish/action.yml
Fixes #2522 
Removes `setup-node` from the `publish` action since users are expected to run `setup-node` themselves. This is because `setup-node` makes changes to the local job and may adversely affect the user's later steps.
> fix: Remove setup-node from the Node.js publish action

- .github/workflows/builder_gradle_slsa3.yml
- .github/workflows/builder_maven_slsa3.yml
- actions/gradle/publish/README.md
- actions/gradle/publish/action.yml
- actions/maven/publish/README.md
- actions/maven/publish/action.yml
- internal/builders/gradle/action.yml
- internal/builders/maven/action.yml
Fixes the following from https://github.com/slsa-framework/slsa-github-generator/issues/2662:
- The internal Action. It must add randomization and return a new output
- The publish / download Actions. They need an additional input for the randomized name.
> chore: make build dirs of java builders unique

- internal/builders/container/README.md
To summarize the PR:
- added the `--bare` option since we are defining the whole image name in `KO_DOCKER_REPO`, if we didn't specify the `--bare` option, the result would be different than the specified in that variable.
- used the `--image-refs` flag
> feat: enhance the ko workflow

- README.md
On the readme, there is a broken link to Adam Korcz's GitHub address. There is a `/` missing on the URL.
This PR fixes it. 😄
> docs: Fixes broken link on the hall of fame section of the  readme

- actions/generator/generic/create-base64-subjects-from-file/action.yml
Fixes an issue with the `base64` call to generate subject data on macOS-based runners.
Fixes and closes slsa-framework/slsa-github-generator#3015.
> fix: generic generator on macos runners

- renovate.json
Makes renovate create PRs for dependency updates monthly rather than weekly.
https://docs.renovatebot.com/presets-schedule/#schedulemonthly
Also sets vulnerability PRs to be scheduled daily.
https://docs.renovatebot.com/configuration-options/#vulnerabilityalerts
> ci: Make renovate schedule monthly

- internal/builders/gradle/action.yml
- internal/builders/maven/action.yml
Reverts slsa-framework/slsa-github-generator#3083
The PR above was merged but does not fix the problem. Need to revert
> fix: Revert "fix: don't move folders if they are already the same

- .github/actions/compute-sha256/action.yml
- .github/actions/create-container_based-predicate/action.yml
- .github/actions/detect-workflow-js/action.yml
- .github/actions/generate-attestations/action.yml
- .github/actions/privacy-check/action.yml
- .github/actions/sign-attestations/action.yml
- .github/actions/verify-token/action.yml
- actions/delegator/setup-generic/action.yml
> chore: Upgrade TypeScript actions to Node 20

- CHANGELOG.md
Adds unreleased changes to the CHANGELOG to make it easier when doing the next release.
> docs: Update changelog with unreleased changes

- .github/actions/secure-download-artifact/action.yml
- .github/actions/secure-download-folder/action.yml
- .github/actions/secure-upload-artifact/action.yml
- .github/workflows/builder_container-based_slsa3.yml
- .github/workflows/builder_go_slsa3.yml
- .github/workflows/generator_generic_slsa3.yml
- .github/workflows/pre-submit.actions.yml
- .github/workflows/pre-submit.e2e.container-based.default.yml
- .github/workflows/pre-submit.e2e.generic.default.yml
- .github/workflows/pre-submit.e2e.go.config-ldflags-main-dir.yml
- .github/workflows/scorecards.yml
- CHANGELOG.md
- SPECIFICATIONS.md
- internal/builders/generic/README.md
Reverts slsa-framework/slsa-github-generator#3312
https://github.com/slsa-framework/slsa-github-generator/issues/3393
> chore: Revert "fix: upload-artifact and download-artifact v4"

- CHANGELOG.md
- README.md
Update changelog for #3350
...
> chore: Update changelog for #3350

- CHANGELOG.md
- README.md
Amend readme text before release
...
> chore: Amend readme text before release

- .github/actions/generate-builder/action.yml
Update slsa-verifier version
To LGTM this PR, verify that the sha256 is the same as in the official release page https://github.com/slsa-framework/slsa-verifier/blob/main/SHA256SUM.md
> chore: Update slsa-verifier version

- .github/actions/secure-download-artifact/action.yml
- .github/actions/secure-download-folder/action.yml
- .github/actions/secure-upload-artifact/action.yml
- .github/workflows/builder_container-based_slsa3.yml
- .github/workflows/builder_go_slsa3.yml
- .github/workflows/generator_generic_slsa3.yml
- .github/workflows/pre-submit.actions.yml
- .github/workflows/pre-submit.e2e.container-based.default.yml
- .github/workflows/pre-submit.e2e.generic.default.yml
- .github/workflows/pre-submit.e2e.go.config-ldflags-main-dir.yml
- .github/workflows/scorecards.yml
- CHANGELOG.md
- SPECIFICATIONS.md
- internal/builders/generic/README.md
Reverts slsa-framework/slsa-github-generator#3398
Following up with 
- https://github.com/slsa-framework/example-trw/pull/3
- https://github.com/slsa-framework/example-package/pull/340
- https://github.com/slsa-framework/slsa-verifier/pull/719
> break: Revert "chore: Revert "fix: upload-artifact and download-artifact v4""

- internal/builders/docker/pkg/builder.go
Fixes #3571. Fixes #3569. Shoutout to @jblebrun who wrote most of the code in this PR and debugged this issue together with me. 
...
> fix: deadlock and improve debugging experience

- CHANGELOG.md
#3576 
First step before a release, marking all "Unreleased" changes in CHANGELOG.md as "v2.0.0"
...
> docs: v.2.0.0: finalize CHANGELOG.md

- .github/workflows/e2e.sign-attestations.schedule.yml
- .github/workflows/pre-submit.actions.yml
- package-lock.json
- package.json
Addresses https://github.com/slsa-framework/slsa-github-generator/issues/3002
Fixes the .github/workflows/e2e.sign-attestations.schedule.yml workflow.
sigstore-js now has its cli tools in a separate package, to be installed with `install -g @sigstore/cli`.
Invoked the workflow from my personal fork
- https://github.com/ramonpetgrave64/slsa-github-generator/actions/runs/8757196289/job/24035331070#step:6:11
```
Verification succeeded
Verification succeeded
```
We can't add this to a pre-submit, because it requires token permissions that are not available to forks' PR runs.
> fix: use @sigstore/cli in e2e.sign-attestations.schedule.yml

- RELEASE.md
A few fixes and additions to the release docs.
- fix the `sed` commands
- add Github container registry auth instructions
related PR https://github.com/slsa-framework/slsa-verifier/pull/761
Manual testing locally.
> fix: Update release docs

- .github/workflows/pre-submit.pr-title.yml
Updates `thehanimo/pr-title-checker` to v1.4.2 and fixes the version comment. This should allow renovate to create PRs to update dependencies again since it's been broken since early Dec 2023.
Fixes #3022
> ci: fix PR title checker

- .github/workflows/schedule.issue-reopener.yml
Adds a new workflow to run [`ianlewis/todo-issue-reopener`](https://github.com/ianlewis/todo-issue-reopener) to reopen issues that are still referenced by TODO comments.
> ci: Add issue reopener

- .github/workflows/pre-submit.lint.yml
- Makefile
- package-lock.json
- package.json
- renovate.json
Fixes renovate config to use the [`config:best-practices`](https://docs.renovatebot.com/presets-config/#configbest-practices) preset rather than the `config:base` preset since `config:base` seems to have gone away at some point.
Also fixes the `schedule` config by using the [`schedule:monthly`](https://docs.renovatebot.com/presets-schedule/#schedulemonthly) preset. The previous `schedule` config seems to have been invalid because "4 am" had  space between "4" and "am" (this was fixed in the `slsa-verifier` repo on https://github.com/slsa-framework/slsa-verifier/pull/727 but was never fixed here).
Also adds a pre-submit to run the [`renovate-config-validator`](https://docs.renovatebot.com/config-validation/) to ensure that renovate config is valid. This pre-submit will need to be made …
> chore: Fix Renovate config

- .github/workflows/pre-submit.lint.yml
- .github/workflows/update-actions-dist-post-commit.yml
- CONTRIBUTING.md
Similar to slsa-verifier's https://github.com/slsa-framework/slsa-verifier/pull/760
This PR adds a manually-invoked workflow to run against renovate-bot's PRs to update the node `dist` folders.
I made one small change to use the `${{ inputs.pr_number }} ` as an environment variable, to harden against [script injection](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#good-practices-for-mitigating-script-injection-attacks). See also https://github.com/slsa-framework/slsa-verifier/pull/771
Also updating shellckeck to fix this lint error:
- https://github.com/slsa-framework/slsa-github-generator/actions/runs/9101693389/job/25019502486#step:4:21
```
Error: input type of workflow_dispatch event must be one of "string", "boolean", "choice", "environment" …
```
> feat: workflow to update actions dist

- renovate.json
- Set `configWarningReuseIssue` to `false`.
Old behavior: Renovate re-opens a old config warning issue.
New behavior: Renovate creates a new config warning issue.
Read the [Renovate docs, `configWarningReuseIssue` config option](https://docs.renovatebot.com/configuration-options/#configwarningreuseissue) to learn more.
@ianlewis mentioned they want Renovate to create a _new issue_ instead of _re-opening_ an old one:
- https://github.com/slsa-framework/slsa-github-generator/pull/3635#issuecomment-2116420633
Here's an example of a Renovate config warning issue that was re-opened by Renovate recently:
- https://github.com/slsa-framework/slsa-github-generator/issues/404
- Manually reviewed configuration change
> chore: allow Renovate to create new config warning issues

- .github/workflows/pre-submit.e2e.maven.yml
Followup to #3746 
Removes the verify job, which won't work, because the ref will be incorrect.
This workflow will only be checking if the builds succeed, and do publish provenance.
- https://github.com/slsa-framework/slsa-github-generator/actions/runs/10115454784/job/27976327657#step:5:1
```
WARNING: Insecure SLSA_VERIFIER_TESTING is enabled.
Verifying artifact ./target/test-java-project-1.21.97.jar: FAILED: invalid ref: "refs/heads/main": unexpected ref type: "heads"
FAILED: SLSA verification failed: invalid ref: "refs/heads/main": unexpected ref type: "heads"
Error: Process completed with exit code 1.
```
The e2e test is executed in this PR, which now passes.
> fix: maven e2e: remove verify job

- .github/workflows/pre-submit.lint.yml
- .golangci.yml
- go.mod
- internal/builders/docker/pkg/builder_test.go
- internal/builders/docker/pkg/common_test.go
- internal/builders/docker/pkg/config_test.go
- internal/builders/go/e2e-presubmits/go.mod
- internal/builders/go/main_test.go
- internal/builders/go/pkg/build_test.go
- internal/builders/go/pkg/config_test.go
- internal/builders/go/pkg/testdata/go/go.mod
- internal/utils/marshal_test.go
- internal/utils/path_test.go
- signing/sigstore/rekor.go
Followup to https://github.com/slsa-framework/slsa-verifier/pull/810
- upgrades to go 1.23.1 and golangci-lint 1.6.1
- makes necessary changes for the linter
- as of go 1.22, no need to make a copy of the loop variable
- change non-string use of `fmt.Errorf(err)` to `fmt.Error(err)`
unit tests continue to pass, as well as the linter
> chore: go1.23.1 golangci lint 1.6.1

- .github/workflows/builder_container-based_slsa3.yml
- .github/workflows/builder_go_slsa3.yml
- .github/workflows/generator_generic_slsa3.yml
- SPECIFICATIONS.md
- internal/builders/generic/README.md
fixes https://github.com/slsa-framework/slsa-github-generator/issues/4031#issuecomment-2549595578.
revert softprops/action-gh-release to v2.1.0
Folks suggest that 2.1.0 is the last known good version. https://github.com/softprops/action-gh-release/issues/556
N/A
> fix: revert softprops/action-gh-release to v2.1.0

- .github/workflows/scripts/pre-submit.e2e.go.default.sh
Update pre-submit to use ubuntu24
https://github.com/slsa-framework/slsa-github-generator/actions/runs/12999310515/job/36254511524?pr=4041
```
Run ./.github/workflows/scripts/pre-submit.e2e.go.default.sh
✖ ubuntu24 == ubuntu22 :: .predicate.invocation.environment.os should be ubuntu22
Error: Process completed with exit code 1.
```
This PR's pre-submits should pass.
> fix: update pre-submit to ubuntu24

- .github/workflows/e2e.sign-attestations.schedule.yml
- .github/workflows/pre-submit.actions.yml
- .github/workflows/pre-submit.lint.yml
- .github/workflows/pre-submit.units.yml
- .github/workflows/scripts/pre-submit.e2e.go.default.sh
start using node22 in all our actions and pre-submits.
re: #4001
The pre-submits in this PR should pass.
> fix: use node 22

- .github/actions/generate-builder/builder-fetch.sh
- .github/workflows/pre-submit.actions.yml
- internal/builders/generic/README.md
#label:release v2.1.0
fixes the jq of a script for the new sigstore bundles.
https://github.com/slsa-framework/example-package/actions/runs/13507076085/job/37739034806#step:2:226
```
jq: parse error: Invalid numeric literal at EOF at line 1, column 3
Error: Process completed with exit code 5.
```
local testing of the same query against the [new provenance](https://github.com/slsa-framework/slsa-github-generator/releases/download/v2.1.0/slsa-builder-docker-linux-amd64.intoto.jsonl).
```
➜  jq -r '.dsseEnvelope.payload' <"$BUILDER_RELEASE_BINARY.intoto.jsonl" | base64 -d | jq -r '.predicate.materials[0].digest.sha1'
fbeecf0c1e9cbb70c6828b0d311037a9e6cce717
```
> fix: fix jq for the sigstore bundles
