github/workflow.go

Remove .git from repo URI

---

cmd/slsa-github-generator/attest.go

Add --predicate cli flag

---

README.md
slsa/github.go
slsa/provenance.go
slsa/provenance_test.go

Add build invocation ID

---

slsa/provenance.go

Allow nil OIDC client. This is needed to implement some level of e2e pre-submits, see https://github.com/slsa-framework/slsa-github-generator-go/pull/73
On pull request triggers, the `id-token` permissions is set to `read` so we cannot use OIDC features. (`write` is needed)
We still want to have pre-submit e2e tests the the extent possible: we will not sign the provenance. Full e2e verification including signature verification is run daily in https://github.com/slsa-framework/example-package/tree/main/.github/workflows and progress tracked in https://github.com/slsa-framework/slsa-github-generator-go/issues/3#issuecomment-1097455581.

✨ Allow nil OIDC client

---

cmd/slsa-github-generator/attest.go
signing/signer.go
signing/sigstore/fulcio.go
signing/sigstore/rekor.go

Adds interfaces which will allow the generator to different signers in the future.

Add Signer and TransparencyLog interfaces.

---

.github/actions/detect-workflow/Dockerfile
.github/workflows/slsa2_provenance.yml

Use detect-workflow action

---

README.md
SPECIFICATIONS.md
builders/generic/README.md
builders/go/README.md

Transfer doc from go repo and re-organize the doc structure.
closes https://github.com/slsa-framework/slsa-github-generator/issues/62
closes https://github.com/slsa-framework/slsa-github-generator/issues/58

✨ Transfer docs from go repo

---

.github/workflows/codeql-analysis.yml

Run CodeQL

---

internal/builders/go/README.md

closes https://github.com/slsa-framework/slsa-github-generator/issues/120

✨ Add section about Goreleaser in doc

---

README.md
internal/builders/go/README.md

Fixes https://github.com/slsa-framework/slsa-github-generator/issues/166

Add provenance field docs for the GitHub hosted build

---

.github/workflows/pre-submit.e2e.generic.workflow.yml
.github/workflows/slsa2_provenance.yml
internal/builders/generic/README.md
internal/builders/generic/attest.go
internal/builders/generic/attest_test.go

Change format of subjects to base64

---

RELEASE.md

docs: add release docs on what e2e verifier tests are needed

---

internal/builders/go/README.md
internal/builders/go/pkg/build.go
internal/builders/go/pkg/build_test.go

Add `{{ .Version }}` which goreleaser supports

✨ Add Version variable

---

CODEOWNERS

Removing myself because I am not actively reviewing PRs.

Remove @MarkLodato from CODEOWNERS

---

.github/actions/detect-workflow/main_test.go
internal/builders/go/pkg/build_test.go

Fixes flakiness in tests, re-ran this 50 times locally in sequence with no failure.

test: use t.Setenv for auto cleanup 

---

internal/builders/go/pkg/provenance.go
signing/signer.go
signing/sigstore/rekor.go

https://github.com/slsa-framework/slsa-github-generator/issues/318

feature: add logging uuid for uploading rekor entries

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Relevant docs:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Add some basic issue templates

---

README.md
internal/builders/generic/README.md
internal/builders/go/README.md

- Update "Golang" to "Go"
- Update the supported triggers section to look nicer.
- Capitalization updates to section headers
- Some formatting changes

Doc updates

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/generator_generic_slsa3.yml

See https://github.com/slsa-framework/slsa-github-generator/issues/363
closes https://github.com/slsa-framework/slsa-github-generator/issues/363

🐛 Fix builder name collision

---

.github/workflows/builder_go_slsa3.yml

This PR https://github.com/slsa-framework/slsa-verifier/pull/104 is already LGTM'ed.
The hash was verified. But you can re-verify it using the steps described in the PR

✨ Bump verifier hash

---

go.mod
internal/builders/go/pkg/build.go

Was this spelling intentional?

Fix spelling of 'Sepcial'

---

renovate.json

closes https://github.com/slsa-framework/slsa-github-generator/issues/404

🐛 Fix renovatebot config

---

renovate.json

closes https://github.com/slsa-framework/slsa-github-generator/issues/404

🐛 Revert removate.json change

---

.github/actions/detect-workflow/README.md
PROVENANCE_FORMAT.md
README.md

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

Fixed typos

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/generator_generic_slsa3.yml

Create a release as part of generic workflow

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/generator_generic_slsa3.yml

Not sure why this didn't trigger an error before?
Maybe wait until https://github.com/slsa-framework/slsa-verifier/pull/114/ is approved

fix: verifier sha refs

---

.github/actions/generate-builder/action.yml
.github/actions/secure-download-artifact/action.yml
.github/actions/secure-upload-artifact/action.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/pre-submit.e2e.generic.default.yml
.github/workflows/pre-submit.e2e.go.config-ldflags-main-dir.yml

Fix part of https://github.com/slsa-framework/slsa-github-generator/issues/452#issuecomment-1171585190
This PR updates the refs for the Actions

fix: update ref for all internal Actions

---

.github/actions/checkout-go/action.yml
.github/actions/secure-download-artifact/action.yml
.github/actions/secure-upload-artifact/action.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/pre-submit.units.yml
internal/builders/generic/README.md
internal/builders/go/README.md

Adds necessary tag= prefix to pinned actions tags so that Renovate can recognize them.

chore: add tag=prefix to pinned actions tags

---

internal/builders/go/README.md

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
fix broken link

fix: broken link

---

internal/builders/generic/README.md

Fix link in README

---

.github/actions/generate-builder/action.yml
.github/actions/generate-builder/generate-builder.sh
.github/workflows/builder_go_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
RELEASE.md

closes https://github.com/slsa-framework/slsa-github-generator/issues/501

feat: Share env variables for pre-built builder binaries

---

.github/actions/generate-builder/action.yml
.github/actions/secure-download-artifact/action.yml
.github/actions/secure-upload-artifact/action.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/generator_generic_slsa3.yml

Update Action hashes to use the rng Action to randomize binary names

feat: bump Action hashes

---

.github/workflows/pre-submit.e2e.generic.default.yml
.github/workflows/pre-submit.e2e.go.config-ldflags-main-dir.yml
.github/workflows/pre-submit.units.yml
internal/builders/generic/attest.go

closes https://github.com/slsa-framework/slsa-github-generator/issues/522

fix: Make pre-submits blocking

---

.github/workflows/codeql-analysis.yml
.github/workflows/pre-submit.actions.yml
.github/workflows/pre-submit.e2e.generic.default.yml

See https://github.com/slsa-framework/slsa-github-generator/issues/547

Set token permissions in workflows

---

internal/builders/generic/README.md

Based on the [example-package](https://github.com/slsa-framework/example-package) example workflows, reduced to the instructions that are needed to build and generate provenance.
Included 2 artifacts in the example, for the scenarios where multiple artifacts are built in the same job.
Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>

Add provenance instruction for Bazel based builds.

---

internal/builders/generic/README.md

doc: add color to snippets

---

internal/builders/generic/README.md

doc: Fix typo

---

internal/builders/generic/README.md

doc: remove comments

---

internal/builders/generic/README.md

Note: I'll update the doc to use cargo

doc: Example for Rust for generic generator

---

internal/builders/generic/README.md

doc: Fix link

---

RELEASE.md

doc: release doc typos

---

internal/builders/generic/README.md

Fixes #353 
Adds doc for the `attestation-name` input to the generic workflow.

Add doc for attestation-name

---

internal/builders/generic/README.md

Update generic README.md for availability

---

renovate.json

feat: Group NodeJs update

---

signing/sigstore/fulcio.go

bug: fix address for fulcio

---

.github/workflows/scorecards.yml

Updated scorecard v2 
Signed-off-by: Naveen <172697+naveensrinivasan@users.noreply.github.com>

Updated scorecard v2

---

.github/actions/checkout-go/action.yml

Follow-up to complete https://github.com/slsa-framework/slsa-github-generator/pull/795

feat: pin verify action by hash

---

README.md

Updated README.md to include Scorecard badge
Signed-off-by: Naveen <172697+naveensrinivasan@users.noreply.github.com>

Updated README.md to include Scorecard badge

---

internal/builders/container/README.md

Add example of using cosign and cue policy

---

.github/actions/verify-checkout/action.yaml

Log the GitHub context

---

.github/actions/secure-checkout/action.yaml

Fix input default values

---

.github/actions/generate-builder/action.yml
.github/workflows/builder_go_slsa3.yml

Restore default inputs for checkout-go

---

.github/actions/secure-checkout/action.yaml

Fix token use in secure-checkout

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_node_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml

Last one! Update the reference for `generate-builder` action, from https://github.com/slsa-framework/slsa-github-generator/commit/325c27afeab313babb4ab9265fa123957da01ac2

update refs for generate-builder

---

.github/workflows/pre-submit.actions.yml

Updates #1068 
After merge we need to add new pre-submits as required in protected branch settings.

Add presumbit checks for internal actions

---

.github/workflows/builder_node_slsa3.yml

Add ref to checkout-node action

---

.github/actions/generate-builder/action.yml

follow-up to https://github.com/slsa-framework/slsa-github-generator/pull/1075

bug: fix path in action

---

.github/actions/secure-project-checkout-go/action.yml
.github/actions/secure-project-checkout-node/action.yml
.github/actions/secure-project-checkout/action.yaml
.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_node_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/pre-submit.actions.yml

Follow-up to https://github.com/slsa-framework/slsa-github-generator/pull/1075
https://github.com/slsa-framework/slsa-github-generator/pull/1085 needs to be merges first.
Prior to release, we will pin these by tag `@vx.y.w` to be in sync with the release tag

bug: additional fixes for ref removal

---

RELEASE.md

See title. Updates to describe how verifier e2e test gen works after releasing builders.

docs: update release.md for generating verifier e2e tests

---

.github/workflows/pre-submit.actions.yml

Fix PR description check for releases

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/pre-submit.actions.yml

Update release tag for v1.2.2

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/pre-submit.actions.yml

Undo code freeze in order to make changes.

Revert "Update release tag for v1.2.2 (#1210)"

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml

Update refs for release 1.2.2

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml

This effectively ends code freeze for the 1.2.2 release.

Update references to main after v1.2.2 release

---

RELEASE.md
internal/builders/generic/README.md
internal/builders/go/README.md

Update docs to use v1.2.2

---

.github/workflows/pre-submit.actions.yml

Fix semver regex in actions pre-submit

---

internal/builders/generic/README.md

Signed-off-by: Dan Albert <danalbert@google.com>

Fix typo in doc.

---

internal/builders/generic/README.md

runs-on is required: https://github.com/DanAlbert/slsa-gradle-example/actions/runs/3500410886
contents write permission is required: https://github.com/DanAlbert/slsa-gradle-example/actions/runs/3500417144

Fix reference Gradle workflow.

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml

Undo the code freeze for v1.3.0 to make changes, such as #1258 

Undo the v1.3.0 freeze

---

internal/builders/generic/README.md

I thought for sure we had fixed all these.
Related: #1240 

Fix permissions in doc

---

.github/workflows/pre-submit.actions.yml

Restore compile-builder pre-submit

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml

Undo the code freeze for #1283 

undo freeze

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/pre-submit.actions.yml
.github/workflows/scripts/pre-release/references.sh

Code freeze
#label:release v1.4.0-rc.1

Code freeze for v1.4.0-rc.1

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml

Initiates code freeze for the v1.4.0-rc.2 release.
#label:release v1.4.0-rc.2

refactor: Update refs to v1.4.0-rc.2

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
RELEASE.md

chore: set references for v1.4.0 release

---

.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
internal/builders/container/README.md
internal/builders/generic/README.md
internal/builders/go/README.md

Finalize v1.4.0 release

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

docs: Use CoC in governance repo

---

internal/builders/container/README.md

docs: Update cosign verification example for v1.4.0

---

internal/builders/docker/pkg/common.go
internal/builders/docker/pkg/common_test.go
internal/builders/docker/testdata/build-definition.json

Ref #1191.
This PR adds structs based on SLSA provenance v1 (https://github.com/slsa-framework/slsa/pull/525).

Add SLSA struct definitions

---

.golangci.yml
github/oidc.go
internal/builders/container/generate.go
internal/builders/docker/commands.go
internal/builders/docker/pkg/common.go
internal/builders/generic/attest.go
internal/builders/generic/attest_test.go
internal/builders/go/pkg/build_test.go
internal/builders/go/pkg/provenance.go
internal/builders/go/pkg/provenance_test.go
internal/builders/nodejs/attest.go
internal/utils/marshal_test.go

Updates #450 
Signed-off-by: Fabian Kammel <fk@edgeless.systems>

ci: Enable and fix lll

---

.github/workflows/scorecards.yml

Fix scorecard action

---

.github/actions/README.md
.github/actions/compute-sha256/README.md
README.md
RELEASE.md
SPECIFICATIONS.md
internal/builders/container/README.md
internal/builders/generic/README.md
internal/builders/go/README.md

No functional changes, just fixing some issues found while looking at the container and generic workflows.
Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>

[NFC] Fix typos, trailing spaces, URLs

---

internal/builders/docker/README.md
internal/builders/docker/commands.go
internal/builders/docker/pkg/builder.go
internal/builders/docker/pkg/builder_test.go
internal/builders/docker/pkg/common.go
internal/builders/docker/pkg/common_test.go
internal/builders/docker/pkg/config.go
internal/builders/docker/pkg/config_test.go
internal/builders/docker/testdata/build-definition.json

Ref #1191 
Builds on top of #1387 and adds builder functionality.
The remaining part is to write the intoto.Subjects for the generated artifacts into a file. I'll do this in a future PR.

Add builder functionality 

---

.github/pr-title-checker-config.json
.github/workflows/pre-submit.pr-title.yml

Updates #1253
Related to https://github.com/slsa-framework/slsa-verifier/issues/371

ci: Add PR title checker

---

CHANGELOG.md

docs: Remove v1.5.0-rc.0 from CHANGELOG

---

internal/runner/runner_test.go

test: Remove sorting in CommandRunner test

---

.github/workflows/pre-submit.pr-title.yml

ci: Explicitly set permissions on pr-title pre-submit

---

internal/builders/container/README.md

docs: Add verification section to container generator docs for slsa-verifier

---

internal/builders/go/README.md

Comments from @ianlewis in https://github.com/slsa-framework/slsa-github-generator/pull/1516

feat: update versions for the Go builder doc

---

.github/workflows/scripts/pre-release/references.sh

chore: Fix typo in comments

---

internal/builders/docker/pkg/builder.go
internal/builders/docker/pkg/builder_test.go

Fixes #1478.
Signed-off-by: Razieh Behjati <razieh@google.com>

fix: Use custom error types in the builder

---

internal/builders/container/README.md

docs: Fix getting image in Ko example

---

.github/workflows/e2e.verify-token.schedule.yml
.github/workflows/scripts/schedule.actions/verify-token.sh

Also for debugging, catted out the predicate.json
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/1588
(hopefully)

fix: fix verify-token rekor_public_log input name change

---

.github/workflows/scripts/e2e-utils.sh

One more fix: https://github.com/slsa-framework/slsa-github-generator/actions/runs/4055979822/jobs/6979852459
systemParamters, at least right now, have "values".
(this may change later with v1.0)

fix: fix verify-token predicate values check

---

.github/workflows/scripts/e2e-verify.common.sh

fix: fix typo in verification script

---

.github/workflows/pre-submit.actions.yml

Fixes https://github.com/slsa-framework/slsa-github-generator/issues/1418
sigstore-js has been updated to fix the rekor.pub issue

fix: add verify-token to check-dist

---

.github/workflows/scripts/pre-release/references.sh

Fixes #1650 
Signed-off-by: Ian Lewis ianlewis@google.com

ci: Don't run refrences.sh on RC releases

---

CONTRIBUTING.md

Fixes #617 
Updates #886 
Restructures the CONTRIBUTING docs to include more info on creating PRs, DCO, and what kinds of issues to take a look at first.
Signed-off-by: Ian Lewis ianlewis@google.com

docs: Update CONTRIBUTING

---

CONTRIBUTING.md

docs: Fix link reference in CONTRIBUTING.md

---

.github/workflows/builder_docker-based_slsa3.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/delegator_generic_slsa3.yml
.github/workflows/e2e.create-docker_based-predicate.schedule.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
CHANGELOG.md
SECURITY.md
internal/builders/container/README.md
internal/builders/generic/README.md
internal/builders/go/README.md

Finalizes release of v1.5.0
#label:release v1.5.0

chore: Release v1.5.0

---

.github/workflows/builder_docker-based_slsa3.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/delegator_generic_slsa3.yml
.github/workflows/e2e.create-docker_based-predicate.schedule.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml

chore: Reference actions at main

---

.github/workflows/builder_docker-based_slsa3.yml
.github/workflows/delegator_generic_slsa3.yml

Fixes https://github.com/slsa-framework/slsa-github-generator/issues/1623
The slsa layout and predicate file are not needed by the end user, so clean these up since they are only uploaded to pass between jobs.

feat: delete internal artifacts in BYO and docker

---

.github/workflows/generator_container_slsa3.yml

Avoid https://github.com/slsa-framework/slsa-github-generator/pull/1762 in the future

fix: pin cosign installation version

---

.github/workflows/builder_docker-based_slsa3.yml

Ref https://github.com/actions/runner/issues/2475

fix: Make sure each docker-based job only cleans up its own files

---

.github/workflows/scripts/pre-release/references.sh
.github/workflows/scripts/pre-submit.actions/references.sh

closes https://github.com/slsa-framework/slsa-github-generator/issues/1681

feat: check ref to workflows

---

.github/workflows/builder_docker-based_slsa3.yml
.github/workflows/pre-submit.e2e.docker-based.default.yml

cc @rbehjati 
Will also see if we are missing the presubmit from required, since it was not picked up from https://github.com/slsa-framework/slsa-github-generator/actions/runs/4438713643

fix: fix action syntax for docker-based workflow

---

.github/workflows/pre-submit.actions.yml
.github/workflows/scripts/pre-submit.actions/secure-upload-folder.sh

fix: Update path for secure-upload-folder pre-submit test

---

.github/actions/generate-builder/action.yml
.github/actions/secure-download-artifact/action.yml
.github/actions/secure-download-folder/action.yml
.github/actions/secure-upload-artifact/action.yml
.github/actions/secure-upload-folder/action.yml
.github/workflows/builder_docker-based_slsa3.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/delegator_generic_slsa3.yml
.github/workflows/e2e.create-docker_based-predicate.schedule.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/release.yml

chore: Update tags for v1.6.0-rc.0 release

---

.github/actions/generate-builder/action.yml
.github/actions/secure-download-artifact/action.yml
.github/actions/secure-download-folder/action.yml
.github/actions/secure-upload-artifact/action.yml
.github/actions/secure-upload-folder/action.yml
.github/workflows/builder_docker-based_slsa3.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/delegator_generic_slsa3.yml
.github/workflows/e2e.create-docker_based-predicate.schedule.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/release.yml

This reverts commit 35e4c67e81645dc3b7af35d339c5845f8933697e (#1921)

chore: Revert "chore: Update tags for v1.6.0-rc.0 release (#1921)"

---

.github/actions/verify-token/package.json

See https://github.com/slsa-framework/slsa-github-generator/pull/1990#discussion_r1166123947

fix: add yaml dependency back in verify-token Action

---

internal/builders/generic/README.md

As suggested at https://github.com/jreleaser/jreleaser/discussions/1334
JReleaser is a release tool similarly as GoReleaser but supports more languages. The project itself uses a workflow as described in this PR to provide provenance.

docs: Add section about JReleaser in doc

---

.github/actions/tscommon/.gitignore
.github/actions/tscommon/Makefile
.github/workflows/pre-submit.actions.yml

fix: dist comparison for tscommon

---

internal/builders/nodejs/README.md

docs: Add doc for Node.js builder outputs

---

.github/workflows/e2e.sign-attestations.schedule.yml

Fixes #2032
Failed to realize that the step was executed in a different working directory so #2029 didn't work.

fix: sign-attestations e2e

---

.github/actions/generate-builder/action.yml
.github/actions/secure-download-artifact/action.yml
.github/actions/secure-download-folder/action.yml
.github/actions/secure-upload-artifact/action.yml
.github/actions/secure-upload-folder/action.yml
.github/workflows/builder_docker-based_slsa3.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/delegator_generic_slsa3.yml
.github/workflows/e2e.create-docker_based-predicate.schedule.yml
.github/workflows/e2e.verify-token.schedule.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/release.yml

We need to merge #1983 before we can perform adversarial tests during release.

chore: Revert v1.6.0-rc.1

---

internal/builders/nodejs/README.md

docs: Update Node.js builder docs

---

internal/builders/nodejs/README.md

Updates the permissions needed in the code snippet, and updates the workflow inputs/outputs.

docs: Fix Node.js builder docs

---

internal/builders/docker/commands.go
internal/builders/docker/pkg/builder.go
internal/builders/docker/pkg/builder_test.go
internal/builders/docker/pkg/config.go
internal/builders/docker/pkg/config_test.go
internal/builders/go/main.go
internal/utils/path.go

Part of https://github.com/slsa-framework/slsa-github-generator/issues/1893

fix: use safe reader in container-based build tool

---

internal/builders/generic/README.md

fix: generic readme matrix syntax

---

.github/workflows/e2e.create-container_based-predicate.schedule.yml

sorry :| one more, this time i testing the command locally.

fix: fix jq script syntax

---

.github/actions/generate-builder/action.yml
.github/actions/secure-download-artifact/action.yml
.github/actions/secure-download-folder/action.yml
.github/actions/secure-upload-artifact/action.yml
.github/actions/secure-upload-folder/action.yml
.github/workflows/builder_container-based_slsa3.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_gradle_slsa3.yml
.github/workflows/builder_maven_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/delegator_generic_slsa3.yml
.github/workflows/delegator_lowperms-generic_slsa3.yml
.github/workflows/e2e.create-container_based-predicate.schedule.yml
.github/workflows/e2e.verify-token.schedule.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/release.yml
actions/delegator/secure-attestations-download/action.yml
actions/nodejs/publish/action.yml
actions/nodejs/secure-attestations-download/action.yml

chore: release candidate v1.7.0-rc.0

---

.github/actions/generate-builder/action.yml
.github/actions/secure-download-artifact/action.yml
.github/actions/secure-download-folder/action.yml
.github/actions/secure-upload-artifact/action.yml
.github/actions/secure-upload-folder/action.yml
.github/workflows/builder_container-based_slsa3.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_gradle_slsa3.yml
.github/workflows/builder_maven_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/delegator_generic_slsa3.yml
.github/workflows/delegator_lowperms-generic_slsa3.yml
.github/workflows/e2e.create-container_based-predicate.schedule.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/release.yml
actions/delegator/secure-attestations-download/action.yml
actions/nodejs/publish/action.yml
actions/nodejs/secure-attestations-download/action.yml

chore: update version references to v1.7.0-rc.1

---

.github/actions/generate-builder/action.yml
.github/actions/secure-download-artifact/action.yml
.github/actions/secure-download-folder/action.yml
.github/actions/secure-upload-artifact/action.yml
.github/actions/secure-upload-folder/action.yml
.github/workflows/builder_container-based_slsa3.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_gradle_slsa3.yml
.github/workflows/builder_maven_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/delegator_generic_slsa3.yml
.github/workflows/delegator_lowperms-generic_slsa3.yml
.github/workflows/e2e.create-container_based-predicate.schedule.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/release.yml
actions/delegator/secure-attestations-download/action.yml
actions/nodejs/publish/action.yml
actions/nodejs/secure-attestations-download/action.yml
internal/builders/container/README.md
internal/builders/docker/README.md
internal/builders/generic/README.md
internal/builders/go/README.md
internal/builders/nodejs/README.md

chore: update documentation and references to v1.7.0

---

Makefile
internal/builders/nodejs/README.md

docs: Update supported events for Node.js builder

---

internal/builders/nodejs/action.yml
internal/builders/nodejs/build.sh
internal/builders/nodejs/generate-layout.sh

Fix the filename processing into attestation name for old versions of npm.

fix: Node.js builder layout filename

---

internal/builders/maven/action.yml

Similar to https://github.com/slsa-framework/slsa-github-generator/pull/2482#discussion_r1281193582
cc @laurentsimon

chore: ref v1.8.0 instead of main

---

.github/actions/generate-builder/action.yml
.github/actions/secure-download-artifact/action.yml
.github/actions/secure-download-folder/action.yml
.github/actions/secure-upload-artifact/action.yml
.github/actions/secure-upload-folder/action.yml
.github/workflows/builder_bazel_slsa3.yml
.github/workflows/builder_container-based_slsa3.yml
.github/workflows/builder_go_slsa3.yml
.github/workflows/builder_gradle_slsa3.yml
.github/workflows/builder_maven_slsa3.yml
.github/workflows/builder_nodejs_slsa3.yml
.github/workflows/delegator_generic_slsa3.yml
.github/workflows/delegator_lowperms-generic_slsa3.yml
.github/workflows/e2e.create-container_based-predicate.schedule.yml
.github/workflows/generator_container_slsa3.yml
.github/workflows/generator_generic_slsa3.yml
.github/workflows/release.yml
actions/delegator/random/action.yml
actions/delegator/secure-attestations-download/action.yml
actions/delegator/secure-download-folder/action.yml
actions/delegator/secure-upload-folder/action.yml
actions/generator/generic/create-base64-subjects-from-file/action.yml
actions/gradle/publish/action.yml
actions/maven/publish/action.yml
actions/nodejs/publish/action.yml
actions/nodejs/secure-attestations-download/action.yml
actions/nodejs/secure-package-download/action.yml
internal/builders/maven/action.yml

chore: Release v1.8.0-rc.2

---

.github/workflows/scripts/pre-release/references.sh
.github/workflows/scripts/pre-submit.actions/references.sh
internal/builders/bazel/action.yml

closes https://github.com/slsa-framework/slsa-github-generator/issues/2550

feat: Update ref check for BYOB Actions

---

internal/builders/gradle/action.yml

Fixes https://github.com/slsa-framework/slsa-github-generator/issues/2643
The following comments are irrelevant and have not been addressed:
1. https://github.com/slsa-framework/slsa-github-generator/pull/2636#discussion_r1295386279 (was already done)
2. https://github.com/slsa-framework/slsa-github-generator/pull/2636#discussion_r1295385635 (the code has been removed)
@ianlewis @laurentsimon PTAL

chore: fix nits in Gradle builder

---

internal/builders/gradle/action.yml

Fixes https://github.com/slsa-framework/example-package/issues/274
cc @laurentsimon

chore: fix wrong output in gradle builder

---

.github/workflows/builder_maven_slsa3.yml

Might be related to https://github.com/slsa-framework/example-package/issues/282

fix: typo in maven builder

---

.github/actions/secure-project-checkout-go/action.yml

blocked on https://github.com/slsa-framework/slsa-github-generator/pull/2682
closes https://github.com/slsa-framework/slsa-github-generator/issues/2661

fix: go-version-file path

---

README.md

This PR fixes three small typos on the Readme 🙏

docs: fixes small typos on the readme

---

SPECIFICATIONS.md

closes https://github.com/slsa-framework/slsa-github-generator/issues/2926

docs: Update SPECIFICATIONS.md

---

.github/workflows/generator_container_slsa3.yml

closes https://github.com/slsa-framework/slsa-github-generator/issues/3006

chore: Bump version of cosign-installer Action

---

.github/workflows/release.yml
README.md

chore: fix release workflow

---

CODEOWNERS

adding myself as CODEOWNERS
...

chore: add ramonpetgrave64 to CODEOWNERS

---

SECURITY.md

Updating SECURITY.md has been missed for the last several releases. This PR adds v2.0.x to SECURITY.md as supported versions. v1.10.x is still included as a version that will receive security updates for now.
NOTE: should have approval from someone listed in the [Security Team](https://github.com/slsa-framework/slsa-github-generator/blob/main/SECURITY.md#security-team) (@laurentsimon, @kpk47, @joshuagl)

docs: Add v2.0.0 to SECURITY.md

---

CHANGELOG.md

Adds links to issues referenced in the CHANGELOG

docs: Add links to CHANGELOG

---

renovate.json

Change Renovate schedule to cron syntax.
Fixes #404
Code inspection only

chore(renovate): use cron syntax for schedule

---

.github/actions/generate-builder/action.yml

Update to slsa-verifier v2.6.0
followup to https://github.com/slsa-framework/slsa-verifier/pull/789
N/A

chore: slsa-verifier v2.6.0: Update action.yml

---

.github/actions/generate-builder/action.yml

Update to slsa-verifier v2.7.0, followup to 
https://github.com/slsa-framework/slsa-verifier/pull/829
Pre-submits in this PR pass.

chore: update to slsa-verifier v2.7.0
